Add steps to simplify approve and lock
oceanprotocol/df-web pull request #371
Opened 2022-11-02 14:11 UTC by KatunaNorbert

Fixes #305.

2022-11-07 05:42 UTC, idiom-bytes commented on src/components/veocean/LockOcean.svelte
> +      currentStep = 1;
I have updated various things under branch => `issue305-review-approve-and-lock`
- Checkbox above the approve button
- Step component at bottom of card
- User should always start at step 0

There is some work to be done here.
- If amount passed into isCurrencyAllowed(amount) == 0, it should return false, not true by default. This should force the user to always start at step 0, not at step 1.
- After the user locks, they should be able to resume from step 1 as long as amount <= 0
- If amount > 0, then step = 0

I spent some time trying to address the details here, inside of the branch.
Please continue to merge the other PRs as appropriate.
Cheers!

2022-11-07 05:51 UTC, idiom-bytes requested changes
I believe there are some adjustments to improve the UX, and that the step component isn't quite there yet. 

I.E. The user often starts at step 1, when they should start at step 0.
- If no lock and amount is 0, then step is 0
- If lock and amount is 0, then step is 1
- if lock and amount > 0, then step is 0
- I think the checkbox might be moved before the Update Lock button.
- I don't think the "Update Lock" button description should change to "Update Lock End Date". Again, I feel we're trying to make things smart, but just adding complexity. Another example is making the "Lock Ocean" card change titles.

Generally, I feel that the number of steps should change, rather than having the step where the user is at change. As described in issue #305. Based on the current implementation, I'm not suggesting we change the step component... just tighten up a bit of how the user flows through the steps.
https://github.com/oceanprotocol/df-web/issues/305

Thank you!

2022-11-07 09:11 UTC, KatunaNorbert commented
I can agree with moving the steps component at the bottom and agreement checkbox above the button but I'm not sure about showing the first step by default.
It doesn't really make sense to show 2nd step at 0 balance when there is a lock and 1st when there isn't. It should be the same outcome since it doesn't rely on have a lock.

2022-11-17 20:05 UTC, idiom-bytes approved these changes

2022-11-17 20:07 UTC, idiom-bytes commented
We went over the code I provided in https://github.com/oceanprotocol/df-web/pull/397 and merged that into this PR.
This now has everything required to deliver the step component, and make it play well w/ the state of the user.

Reviewed implementation w/ Katuna

2022-11-17 20:20 UTC, idiom-bytes commented
Tested/reviewed. Merging.

2022-11-17 20:20 UTC, merged