Rename Volume DF table header terms
oceanprotocol/df-web pull request #659
Opened 2023-11-01 13:31 UTC by KatunaNorbert

Fixes #655.

2023-11-07 03:14 UTC, idiom-bytes requested changes
Couple of details left to complete all feedback

2023-11-07 03:14 UTC, idiom-bytes commented on src/utils/metadata/descriptions.json
> +  "tooltip_datafarming_3_round_consume": "Average Data Consume Volume of a Dataset for the last 3 Data Farming rounds.",
Change from "last" => "previous"

2023-11-07 03:14 UTC, idiom-bytes commented on src/utils/metadata/descriptions.json
> +  "tooltip_datafarming_3_round_allocation": "Average veOCEAN amount allocated to a Dataset across all users in the last 3 rounds.",
Change from "last" => "previous"

2023-11-08 12:55 UTC, KatunaNorbert commented
@idiom-bytes has requested some changes and needs to give approval before I can merge

2023-11-08 15:49 UTC, idiom-bytes approved these changes
lgtm

2023-11-08 15:52 UTC, merged